#Tên Project
name: 'dbtvault_project'
version: '0.1.0'
require-dbt-version: ['>=1.0.0', '<2.0.0']
config-version: 2

# "profile" cấu hình db cho project này
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  #Code đã được biên dịch thành SQL
clean-targets:         #Thử mục bị xóa khi chạy `dbt clean`
  - "target"
  - "dbt_packages"

#Truyền tham số khi chạy 1 batch dbt
vars:
  load_date: '2023-04-12'
  applied_date: '1992-01-08'
  fake_address: 'B'
  tpch_size: 1 #1, 10, 100, 1000, 10000
  "dbt_date:time_zone": "Asia/Ho_Chi_Minh"
  hash: MD5 # or SHA
  enable_ghost_records: true
  system_record_value: 'DBTVAULT_SYSTEM'
  bronze_layer: "azure://nghialake.blob.core.windows.net/nghiafile/Data/Bronze"
# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  dbtvault_project:
      1_raw_staging:
        tags:
          - 'raw'
        materialized: table
      2_hashed_staging:
        tags:
          - 'hash'
        materialized: view
      3_raw_vault:
        tags:
        - 'raw_vault'
        materialized: incremental
      4_business_vault:
        materialized: view
        hubs:
          tags:
            - 'hub'
        links:
          tags:
            - 'link'
        satellite:
          tags:
            - 'satellite'
      5_marts:
        materialized: view
        uss2:
          tags:
            - 'uss2'